services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-github-bridge
    environment:
      NODE_ENV: 'development'
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0
    container_name: discord-github-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discord_github
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
